/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_cloudwalk_camera_GetCameraStreamJNI */

#ifndef _Included_cn_cloudwalk_camera_IdcarDetectionJNI
#define _Included_cn_cloudwalk_camera_GetCameraStreamJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_cloudwalk_camera_GetCameraStreamJNI
 * Method:    GetCameraStreamJNIOpen
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_cn_cloudwalk_camera_GetCameraStreamJNI_Open
  (JNIEnv *, jclass,jstring, jint timeout_ms,jboolean,jboolean);

JNIEXPORT jint JNICALL Java_cn_cloudwalk_camera_GetCameraStreamJNI_Pause
  (JNIEnv *, jclass,jboolean);


/*
 * Class:     cn_cloudwalk_camera_GetCameraStreamJNI
 * Method:    GetCameraStreamJNIGetImage
 * Signature: ([BII)I
 */
JNIEXPORT jbyteArray JNICALL Java_cn_cloudwalk_camera_GetCameraStreamJNI_GetImage
  (JNIEnv *, jclass,jint);

  /*
 * Class:     cn_cloudwalk_camera_GetCameraStreamJNI
 * Method:    GetCameraStreamJNIGetMediaInfo
 * Signature: ([BII)I
 */
JNIEXPORT jobject JNICALL Java_cn_cloudwalk_camera_GetCameraStreamJNI_GetMediaInfo
  (JNIEnv *, jclass);
  
/*
 * Class:     cn_cloudwalk_camera_GetCameraStreamJNI
 * Method:    GetCameraStreamJNIClose
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cn_cloudwalk_camera_GetCameraStreamJNI_Close
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
